### ISSUE TITLE
Env vars

### ISSUE THREAD

**Issue by rapcal** [digitalocean/sample-rails#2]
Is it possible to import env vars from a yaml file or directly from the `heroku:config` command?

**Comment by kamaln7** [comment]
Hi @rapcal, unfortunately there isn't a way to import env vars right now. We're exploring some options for the UI, like drag-and-dropping or pasting a `.env` file. The closest you can get is to export your app spec, add all the env vars to it, and then save it:

1. [Install doctl](https://www.digitalocean.com/docs/apis-clis/doctl/how-to/install/)
2. List your apps and find your app's UUID: `doctl apps list`
3. Save your app's spec to a file: `doctl apps spec get APP-UUID > app.yaml`
4. Open `app.yaml` in a text editor and add the env vars to your component(s).
5. Update your app with the new spec: `doctl apps update --spec app.yaml APP-UUID`. This will kick off a new deployment.

See [the App Specification Reference](https://www.digitalocean.com/docs/app-platform/references/app-specification-reference/) for more info about app specs.
