### ISSUE TITLE
Unclear as how to serve assets

### ISSUE THREAD

**Issue by kshahkshah** [digitalocean/sample-rails#21]
I've stood up my app after a bunch of trial and error on the app platform, but can't figure out how to get assets in the public folder, served without 404'ing.

I've flipped `RAILS_SERVE_STATIC_FILES` to true and added `/assets` to the list of HTTP request routes.

Anyone run into this? Solve it? I'm happy to update the README

**Comment by ElanHasson** [comment]
Hi @whistlerbrk, I see you closed the issue-- were you able to resolve it? 

If so, what was the issue and how did you resolve it? 

If not, I can lend a hand.
