### ISSUE TITLE
 BuildJobTimeout

### ISSUE THREAD

**Issue by prashanth726** [digitalocean/sample-rails#3]
My Ruby application failed to deploy with **Error : BuildJobTimeout Your build job failed because it timed out after 20 minutes**.. How do i increase the deployment time when deploying for Digital Ocean Apps. Or can i keep pre-deploy command to make deploy faster

**Comment by manuelmeurer** [comment]
The timeout was increased to 60 minutes, apparently a few days after you ran into the problem. 😄

https://www.digitalocean.com/community/questions/buildjobtimeout-in-ruby-on-rails-application-in-digital-ocean-app-platform?answer=64511

**Comment by kamaln7** [comment]
Sorry we missed this issue. Thanks @manuelmeurer!
