### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by tobsch** [digitalocean/sample-rails#6]
Hi,

how and when are migrations being run here?

**Comment by kamaln7** [comment]
👋 @tobsch 

Migrations aren't run by default. There are a few different approaches:

1. Run migrations manually when needed, in the live console in the control panel
3. Run migrations as a pre-deployment job, see [How to Manage Jobs in App Platform](https://www.digitalocean.com/docs/app-platform/how-to/manage-jobs/)
2. Run migrations as part of the run command. For example, you could set your run command to `rake db:migrate && rails server -p $PORT -e ${RAILS_ENV:-production}`. This is also a correct way but note that if your migrations take a "long time" to run and delay the server start, App Platform might think that your app failed to deploy. You can increase the initial health check timeout by adjusting the [`services[].health_check.initial_delay_seconds`](https://www.digitalocean.com/docs/app-platform/references/app-specification-reference/#ref-services-health_check-initial_delay_seconds) option in your app spec.

I hope that helps!

**Comment by urchymanny** [comment]
running `bin/rails db:migrate` doesn't work on console so, adding it to your run command is the only solution for now

**Comment by cappe** [comment]
Happened to stumble on this thread so leaving a comment for the future reference:

If your approach is to run migrations manually through the live console in the DO control panel, the correct command would be `bundle exec rails db:migrate`. I spent shameful amount of time figuring that out. I think it's about the command setting up the correct environment or something.

Also, I'd suggest not to use Approach 3. My understanding is that you may end up running the migrations multiple time unnecessarily. Most importantly, if the thing timeouts, you end up spending time on debugging hiccups that are may not be easy to reproduce. Increasing the timeout on the App Spec feels hacky.

I strongly recommend using the Approach 2 as it's a set-and-forget. If the migrations fail to run, the app won't get deployed, but leaves the previous deployment up. No need to debug weird timeout issues.

**Comment by beydogan** [comment]
@kamaln7 

> Run migrations as part of the run command. For example, you could set your run command to rake db:migrate && rails server -p $PORT -e ${RAILS_ENV:-production}. This is also a correct way

If you have multiple app containers, won't this cause all migrations to run in parallel since its in the run command?
